[project]
name = "cwhpp"
version = "0.1.0"
description = "Country Wide Housing Prices Predictions"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lightgbm>=4.6.0",
    "pandas>=2.3.2",
    "polars>=1.33.1",
    "scikit-learn<1.8",
]

